# config/production.yaml
logging:
  level: "INFO"
  file: "/var/log/wikimedia_access.log"
  max_size_mb: 20
  backup_count: 10
  console: false  # Pas de logs console en prod

monitoring:
  enabled: true
  metrics_collection_interval: 60
  health_check_interval: 300

alerts:
  enabled: true
  error_rate_threshold: 5.0    # Plus strict en prod
  response_time_threshold: 2000
  cooldown_duration: 600       # 10 minutes en prod

retry:
  max_attempts: 3
  backoff_factor: 2.0          # Plus agressif en prod
  timeout: 45

validation:
  strict_mode: true
  validate_responses: true

cache:
  default_ttl: 1800  # 30 minutes en prod
  cleanup_interval: 7200
  